export const ACTIONS = {
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TOD",
  TOGGLE_TODO: "TOGGLE_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  ERROR: "ERROR",
  SHOW_MODAL: "SHOW_MODAL",
  ADD_TITLE: "ADD_TITLE",
  TOGGLE_UPDATE: "TOGGLE_UPDATE",
};
